version: 0.0
os: linux
files:
  - source: / # Specifies the source location of the files
    destination: /var/www/myapp # Specifies the destination on the EC2 instance

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
