version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react-app
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_react_server.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
